### ISSUE TITLE
How does this work compare to CIHP_PGN?

### ISSUE THREAD

**Issue by andrewjong** [HCPLab-SYSU/ATEN#8]
Hi, I'm looking at both your work and [CIHP_PGN](https://github.com/Engineering-Course/CIHP_PGN). The conclusions from both your papers are _very_ similar.

[CIHP_PGN Paper](https://arxiv.org/abs/1808.00157)
> In this paper, we presented a novel detection-free Part Grouping Network to investigate **instance-level human parsing, which is a more pioneering and challenging work in analyzing human in the wild**. To push the research boundary of human parsing to match real-world scenarios much better, we further introduce a new large-scale (...)
> Experimental results on PASCAL-Person-Part [6] and our CIHP dataset **demonstrate the superiority of our proposed approach**, which surpasses previous methods for both semantic part segmentation and edge detection tasks, and **achieves state-of-the-art performance for instance-level human parsing**.

[Your Paper](https://arxiv.org/abs/1808.00661)
> In this work, we investigate video **instance-level human parsing that is a more pioneering and realistic task in analyzing human in the wild**. To fill the blank of video human parsing data resources, we further introduce a large-scale (...)
> Experimental results on DAVIS [36] and our VIP dataset **demonstrate the superiority of our proposed approach**, which **achieves state-of-the-art performance on** both video **instance-level human parsing** and video segmentation tasks.

I'm wondering - which produces better accuracy, this work or CIHP_PGN? Considering that both claim "more pioneering", "demonstrate the superiority of our proposed approach", and "achieve state-of-the-art", can you help explain the differences? I'm not clear which I should use. Thanks!

**Comment by fasogbon** [comment]
Thank you for the question. I am also curious. Thanks

**Comment by fasogbon** [comment]
Or even time complexity

**Comment by zhouqixian** [comment]
Thanks for your interest in our work! Actually, PGN and ATEN are different framework for Image Instance-level Human Parsing and Video Instance-level Human parsing. Consequently, ATEN is designed for video segmentation task where temporal consistency and time efficiency play an important role. PGN achieves state-of-the-art performance on image domain instance-level human parsing, obtaining the best performance on CIHP dataset. ATEN performs well on VIP dataset which is a large-scale video instance-level human parsing dataset. Because of the limitations of memory and processing speed, ATEN just employed a light CNN(ResNet50) as backbone while PGN use ResNet101. Moreover, PGN use multi-scale inference strategy which is proved to be an effective but time consuming method and ATEN use single scale inference.

**Comment by fasogbon** [comment]
Dear zhouqixian, I just have a quick question. Do you think I can still use your approach on about 1-3 images from the same single subject without too much modification?
